// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy2lH5jjrUnXLhb0fFwdNleZduGwZaStQ',
    appId: '1:922030945728:web:e8e8e97af8ccd95707c425',
    messagingSenderId: '922030945728',
    projectId: 'mynotes-47452',
    authDomain: 'mynotes-47452.firebaseapp.com',
    storageBucket: 'mynotes-47452.appspot.com',
    measurementId: 'G-9S5F44496D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnYlGr_cHzKY3HlCeB-sfz5M5-JTjYfbs',
    appId: '1:922030945728:android:9e52c88bfe84a6fd07c425',
    messagingSenderId: '922030945728',
    projectId: 'mynotes-47452',
    storageBucket: 'mynotes-47452.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKryAF24LAqBsfCdMlEfIkomswa5YJfm8',
    appId: '1:922030945728:ios:3d18a3f0e3c4f86007c425',
    messagingSenderId: '922030945728',
    projectId: 'mynotes-47452',
    storageBucket: 'mynotes-47452.appspot.com',
    iosClientId: '922030945728-q6357281go53qanm8omihh0e1bbk5g3o.apps.googleusercontent.com',
    iosBundleId: 'com.example.myNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKryAF24LAqBsfCdMlEfIkomswa5YJfm8',
    appId: '1:922030945728:ios:3d18a3f0e3c4f86007c425',
    messagingSenderId: '922030945728',
    projectId: 'mynotes-47452',
    storageBucket: 'mynotes-47452.appspot.com',
    iosClientId: '922030945728-q6357281go53qanm8omihh0e1bbk5g3o.apps.googleusercontent.com',
    iosBundleId: 'com.example.myNotes',
  );
}
